### ISSUE TITLE
question on processor requirements for running kAFL

### ISSUE THREAD

**Issue by nusnauyiy** [IntelLabs/kAFL#106]
Hello,

I am trying to run this repo, and I am a little confused with the platform requirements as I am quite new to the this. I am currently using a machine with Intel(R) Xeon(R) Platinum 8168 CPU, and it doesn't have `intel_pt`.  The `README` file and #19 leads me to think that even without this requirement, I am able to run the program by patching the kernel. Is this the case? If so, may I get some pointers on how to do this?

Thanks in advance!

**Comment by il-steffen** [comment]
Are you sure you don't have Intel PT - We are using some 2nd and 3rd gen Skylake and so far it seems to be consistently enabled in all SKUs.

There is a fallback option in QemuNyx to work on a standard kernel (using VMware backdoor and standard PML support in KVM). Instead of using Intel PT, QemuNyx also allows you to fill the coverage bitmap in your own way, for instance using SW instrumentation. The first part is performed automatically when QemuNyx detects that the kernel is not patched. The second part is something you have to configure during agent initialization. For instance, it may be possible to set `agent_tracing=1` here and use Linux KCOV to fill the bitmap at `trace_buffer_vaddr`: https://github.com/IntelLabs/kafl.linux/blob/kafl/fuzz-5.15-4/arch/x86/kernel/kafl-agent.c#L240

We are not using any of these options in the kAFL setup, so there might be some minor fixes required.
