### ISSUE TITLE
There is an error in windows Tutorial

### ISSUE THREAD

**Issue by 5angjun** [IntelLabs/kAFL#220]
I recommanded you to test your `windows tutorial` in Cleaned ubuntu 22.04

I use intel i-7 12700K CPU that supported intel PT.
`
bob@bob:~/Desktop$ uname -a
Linux bob 6.0.0-nyx+ #1 SMP PREEMPT_DYNAMIC Wed Mar 8 22:55:35 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
bob@bob:~/Desktop$ 
`

Can i have a feedback from this issue?

```

### Error occured in this Stage ##
cd ../../windows_x86_64
make init
```

![스크린샷 2023-09-02 16-10-10](https://github.com/IntelLabs/kAFL/assets/76202024/1cff1b27-bd56-4ba3-b157-5df3818e16d0)

**Comment by 5angjun** [comment]
I found the solution of this problem

Need to Run All command & script in User mode not Super root mode.

I think you add the warning message that alert to user to run Ansible or make command  in user mode.

**Comment by Wenzel** [comment]
hi @5angjun 

Thank you for taking the time to share your experience and the solution you found.
We appreciate your contribution to the project.

Indeed, we assume that all the commands will be run as non-root user, since root is only required for administrative tasks.
As this is common practise among Linux users, I don't think adding a note is necessary in the documentation as this point.

If this type of issue is raising again, I will consider it however.

Again, thank you for your inputs and feel free to open more issue, should you encounter any problem with kAFL.
