### ISSUE TITLE
Packer needs qemu-img

### ISSUE THREAD

**Issue by M3noetius** [IntelLabs/kAFL#228]
Good afternoon,

In order to compile QEMU-NYX the --disable--tools is disabled [[here](https://github.com/nyx-fuzz/QEMU-Nyx/blob/qemu-nyx-4.2.0/compile_qemu_nyx.sh#L56)]. 

Am I suppose to go to QEMU-nyx master [[here](https://github.com/nyx-fuzz/QEMU-Nyx/tree/master)] and compile the tool ? 
I see that the changes are at the "block-backend.c" and I guess this will have an affect on the image used. [[here](https://github.com/nyx-fuzz/QEMU-Nyx/blob/qemu-nyx-4.2.0/block/block-backend.c#L50)] [[git_blame](https://github.com/nyx-fuzz/QEMU-Nyx/commit/cd702b528c25655632fe3d3c720cdf55a6b9ca9d#diff-a75c6eb35db61021f6306b7c74a9ce914875909178f9cb244ceccf221de3de32R344)]

```
~/kAFL/kafl/examples/templates/windows$ make build 
make[1]: Entering directory '/home/user/kAFL/kafl/examples/templates/windows'
packer init windows.pkr.hcl
source /home/user/kAFL/kafl/examples/templates/windows/../../venv/bin/activate && packer build -var-file win10.pkrvars.hcl windows.pkr.hcl
qemu.windows: output will be in this color.

Build 'qemu.windows' errored after 571 microseconds: Failed creating Qemu driver: exec: "qemu-img": executable file not found in $PATH

==> Wait completed after 600 microseconds

==> Some builds didn't complete successfully and had errors:
--> qemu.windows: Failed creating Qemu driver: exec: "qemu-img": executable file not found in $PATH
``` 

Thank you

**Comment by Wenzel** [comment]
Hi @M3noetius and thank you for opening an issue.

I wasn't aware of the problem you are reporting, since I'm simply relying on the system package to get `qemu-img` tool, from `/usr/bin/qemu-img` (`qemu-system-x86` package).

I'm not fully understanding all the QEMU-Nyx modifications at this stage.
However, the `BlockBackend` struct seems to be defined when QEMU_NYX is **undefined**.
``` c
#ifndef QEMU_NYX
struct BlockBackend {
    char *name;
    int refcnt;
    BdrvChild *root;
```

and judging from the `blk_new` functions, the only field added by Nyx is the `cow_cache`:
https://github.com/nyx-fuzz/QEMU-Nyx/blob/qemu-nyx-4.2.0/block/block-backend.c#L345

In any case, Packer and the Windows template here isn't configured to use the QEMU-Nyx binary that you built previously.
In fact, the `PATH` hasn't been modified to include `kafl/kafl/qemu/x86_64-softmmu/qemu-system-x86_64`.

So in my case, I also the system packaged QEMU to build the Windows template, and then fuzz it with QEMU-Nyx, doesn't seem to be a problem.

@il-steffen can you shed some lights regarding the `block-backend.c` modifications, and whether they are relevant for QEMU images being built ?

**Comment by Wenzel** [comment]
Closed by https://github.com/IntelLabs/kAFL/pull/234
